"""Added CASCADE to the room model

Revision ID: 2d33158004d6
Revises: 0d2e8c3ce1bb
Create Date: 2026-06-29 12:03:08.296226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d33158004d6'
down_revision: Union[str, Sequence[str], None] = '0d2e8c3ce1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_creator_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['creator_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_creator_id_fkey'), 'rooms', 'users', ['creator_id'], ['user_id'])
    # ### end Alembic commands ###
