"""add creator_id to chat_rooms

Revision ID: 84327d960620
Revises: 87aa49f26a90
Create Date: 2026-06-16 16:39:48.102652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84327d960620'
down_revision: Union[str, Sequence[str], None] = '87aa49f26a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_rooms', 'users', ['creator_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_column('chat_rooms', 'creator_id')
    # ### end Alembic commands ###
