"""create chat_rooms table

Revision ID: 87aa49f26a90
Revises: 3d15fca4b366
Create Date: 2026-06-16 16:26:41.768846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aa49f26a90'
down_revision: Union[str, Sequence[str], None] = '3d15fca4b366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('chat_room_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chat_room_id'),
    sa.UniqueConstraint('chat_room_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
