"""create messages table

Revision ID: eb0e12589cd8
Revises: f27d1003dc38
Create Date: 2026-06-19 11:45:22.569005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb0e12589cd8'
down_revision: Union[str, Sequence[str], None] = 'f27d1003dc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_name')
    )
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], name=op.f('chat_rooms_creator_id_fkey')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('chat_rooms_pkey')),
    sa.UniqueConstraint('room_name', name=op.f('chat_rooms_room_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('rooms')
    # ### end Alembic commands ###
